site_name: Jumper Wrapper Kernel
site_description: A Jupyter kernel that wraps other kernels with jumper-extension support
repo_url: https://github.com/ScaDS/jumper_wrapper_kernel
repo_name: ScaDS/jumper_wrapper_kernel

docs_dir: docs

theme:
  name: material
  logo: img/JUmPER01.svg

nav:
  - Home: index.md
  - Getting started:
      - Installation: getting-started/installation.md
      - Quickstart: getting-started/quickstart.md
  - User Guide:
      - Magic Commands: guides/magic-commands.md
      - Auto-Wrap Kernels: guides/wrap-kernel.md
  - API Reference:
      - Overview: api/index.md
      - Kernel: api/kernel.md
      - Installation: api/install.md
      - Utilities: api/utilities.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - mkdocstrings
